@echo off
echo /////////%0 start

cd %~dp0
cd ../
set "SETUP_ROOT=%cd%"
cd %SETUP_ROOT%

set "IN_RELEASE64_DIR=%SETUP_ROOT%\BoltExtlibs\_build\windows\bin\release64"
set "IN_DEBUG64_DIR=%SETUP_ROOT%\BoltExtlibs\_build\windows\bin\debug64"
set "OUT_RELEASE64_DIR=%SETUP_ROOT%\Windows\BoltCore-VS2017\BoltCore\x64\Release"
set "OUT_DEBUG64_DIR=%SETUP_ROOT%\Windows\BoltCore-VS2017\BoltCore\x64\Debug"
set "OUT_CONSOLEDEBUG64_DIR=%SETUP_ROOT%\Windows\BoltCore-VS2017\BoltCore\x64\ConsoleDebug"
mkdir "%OUT_RELEASE64_DIR%"
mkdir "%OUT_DEBUG64_DIR%"
mkdir "%OUT_CONSOLEDEBUG64_DIR%"
xcopy /s /e /h /y "%IN_RELEASE64_DIR%" "%OUT_RELEASE64_DIR%"
xcopy /s /e /h /y "%IN_DEBUG64_DIR%" "%OUT_DEBUG64_DIR%"
xcopy /s /e /h /y "%IN_DEBUG64_DIR%" "%OUT_CONSOLEDEBUG64_DIR%"

taskkill /F /IM vctip.exe
rmdir /s /q %SETUP_ROOT%\SFML\_build
rmdir /s /q %SETUP_ROOT%\tinyxml2\_build

mkdir "%SETUP_ROOT%/Windows/BoltCore-VS2017/BoltCore/Lib"
xcopy /s /e /h /y "%SETUP_ROOT%/BoltExtlibs/cpython/Lib" "%SETUP_ROOT%/Windows/BoltCore-VS2017/BoltCore/Lib"

set "PYTHON_BUILD_ROOT=%SETUP_ROOT%\BoltExtlibs\cpython\PCBuild\amd64"
copy "%PYTHON_BUILD_ROOT%\_asyncio.pyd"				"%OUT_RELEASE64_DIR%\_asyncio.pyd"
copy "%PYTHON_BUILD_ROOT%\_bz2.pyd" 				"%OUT_RELEASE64_DIR%\_bz2.pyd"
copy "%PYTHON_BUILD_ROOT%\_contextvars.pyd" 		"%OUT_RELEASE64_DIR%\_contextvars.pyd"
copy "%PYTHON_BUILD_ROOT%\_ctypes.pyd" 				"%OUT_RELEASE64_DIR%\_ctypes.pyd"
copy "%PYTHON_BUILD_ROOT%\_decimal.pyd" 			"%OUT_RELEASE64_DIR%\_decimal.pyd"
copy "%PYTHON_BUILD_ROOT%\_distutils_findvs.pyd"	"%OUT_RELEASE64_DIR%\_distutils_findvs.pyd"
copy "%PYTHON_BUILD_ROOT%\_elementtree.pyd"			"%OUT_RELEASE64_DIR%\_elementtree.pyd"
copy "%PYTHON_BUILD_ROOT%\_hashlib.pyd"				"%OUT_RELEASE64_DIR%\_hashlib.pyd"
copy "%PYTHON_BUILD_ROOT%\_lzma.pyd"				"%OUT_RELEASE64_DIR%\_lzma.pyd"
copy "%PYTHON_BUILD_ROOT%\_msi.pyd"					"%OUT_RELEASE64_DIR%\_msi.pyd"
copy "%PYTHON_BUILD_ROOT%\_multiprocessing.pyd"		"%OUT_RELEASE64_DIR%\_multiprocessing.pyd"
copy "%PYTHON_BUILD_ROOT%\_overlapped.pyd"			"%OUT_RELEASE64_DIR%\_overlapped.pyd"
copy "%PYTHON_BUILD_ROOT%\_queue.pyd"				"%OUT_RELEASE64_DIR%\_queue.pyd"
copy "%PYTHON_BUILD_ROOT%\_socket.pyd"				"%OUT_RELEASE64_DIR%\_socket.pyd"
copy "%PYTHON_BUILD_ROOT%\_sqlite3.pyd"				"%OUT_RELEASE64_DIR%\_sqlite3.pyd"
copy "%PYTHON_BUILD_ROOT%\_ssl.pyd"					"%OUT_RELEASE64_DIR%\_ssl.pyd"
copy "%PYTHON_BUILD_ROOT%\_tkinter.pyd"				"%OUT_RELEASE64_DIR%\_tkinter.pyd"
copy "%PYTHON_BUILD_ROOT%\pyexpat.pyd"				"%OUT_RELEASE64_DIR%\pyexpat.pyd"
copy "%PYTHON_BUILD_ROOT%\select.pyd"				"%OUT_RELEASE64_DIR%\select.pyd"
copy "%PYTHON_BUILD_ROOT%\unicodedata.pyd"			"%OUT_RELEASE64_DIR%\unicodedata.pyd"
copy "%PYTHON_BUILD_ROOT%\winsound.pyd"				"%OUT_RELEASE64_DIR%\winsound.pyd"

copy "%PYTHON_BUILD_ROOT%\_asyncio_d.pyd"			"%OUT_DEBUG64_DIR%\_asyncio_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_bz2_d.pyd" 				"%OUT_DEBUG64_DIR%\_bz2_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_contextvars_d.pyd" 		"%OUT_DEBUG64_DIR%\_contextvars_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_ctypes_d.pyd" 			"%OUT_DEBUG64_DIR%\_ctypes_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_decimal_d.pyd" 			"%OUT_DEBUG64_DIR%\_decimal_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_distutils_findvs_d.pyd"	"%OUT_DEBUG64_DIR%\_distutils_findvs_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_elementtree_d.pyd"		"%OUT_DEBUG64_DIR%\_elementtree_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_hashlib_d.pyd"			"%OUT_DEBUG64_DIR%\_hashlib_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_lzma_d.pyd"				"%OUT_DEBUG64_DIR%\_lzma_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_msi_d.pyd"				"%OUT_DEBUG64_DIR%\_msi_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_multiprocessing_d.pyd"	"%OUT_DEBUG64_DIR%\_multiprocessing_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_overlapped_d.pyd"		"%OUT_DEBUG64_DIR%\_overlapped_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_queue_d.pyd"				"%OUT_DEBUG64_DIR%\_queue_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_socket_d.pyd"			"%OUT_DEBUG64_DIR%\_socket_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_sqlite3_d.pyd"			"%OUT_DEBUG64_DIR%\_sqlite3_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_ssl_d.pyd"				"%OUT_DEBUG64_DIR%\_ssl_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_tkinter_d.pyd"			"%OUT_DEBUG64_DIR%\_tkinter_d.pyd"
copy "%PYTHON_BUILD_ROOT%\pyexpat_d.pyd"			"%OUT_DEBUG64_DIR%\pyexpat_d.pyd"
copy "%PYTHON_BUILD_ROOT%\select_d.pyd"				"%OUT_DEBUG64_DIR%\select_d.pyd"
copy "%PYTHON_BUILD_ROOT%\unicodedata_d.pyd"		"%OUT_DEBUG64_DIR%\unicodedata_d.pyd"
copy "%PYTHON_BUILD_ROOT%\winsound_d.pyd"			"%OUT_DEBUG64_DIR%\winsound_d.pyd"

copy "%PYTHON_BUILD_ROOT%\_asyncio_d.pyd"			"%OUT_CONSOLEDEBUG64_DIR%\_asyncio_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_bz2_d.pyd" 				"%OUT_CONSOLEDEBUG64_DIR%\_bz2_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_contextvars_d.pyd" 		"%OUT_CONSOLEDEBUG64_DIR%\_contextvars_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_ctypes_d.pyd" 			"%OUT_CONSOLEDEBUG64_DIR%\_ctypes_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_decimal_d.pyd" 			"%OUT_CONSOLEDEBUG64_DIR%\_decimal_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_distutils_findvs_d.pyd"	"%OUT_CONSOLEDEBUG64_DIR%\_distutils_findvs_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_elementtree_d.pyd"		"%OUT_CONSOLEDEBUG64_DIR%\_elementtree_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_hashlib_d.pyd"			"%OUT_CONSOLEDEBUG64_DIR%\_hashlib_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_lzma_d.pyd"				"%OUT_CONSOLEDEBUG64_DIR%\_lzma_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_msi_d.pyd"				"%OUT_CONSOLEDEBUG64_DIR%\_msi_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_multiprocessing_d.pyd"	"%OUT_CONSOLEDEBUG64_DIR%\_multiprocessing_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_overlapped_d.pyd"		"%OUT_CONSOLEDEBUG64_DIR%\_overlapped_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_queue_d.pyd"				"%OUT_CONSOLEDEBUG64_DIR%\_queue_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_socket_d.pyd"			"%OUT_CONSOLEDEBUG64_DIR%\_socket_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_sqlite3_d.pyd"			"%OUT_CONSOLEDEBUG64_DIR%\_sqlite3_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_ssl_d.pyd"				"%OUT_CONSOLEDEBUG64_DIR%\_ssl_d.pyd"
copy "%PYTHON_BUILD_ROOT%\_tkinter_d.pyd"			"%OUT_CONSOLEDEBUG64_DIR%\_tkinter_d.pyd"
copy "%PYTHON_BUILD_ROOT%\pyexpat_d.pyd"			"%OUT_CONSOLEDEBUG64_DIR%\pyexpat_d.pyd"
copy "%PYTHON_BUILD_ROOT%\select_d.pyd"				"%OUT_CONSOLEDEBUG64_DIR%\select_d.pyd"
copy "%PYTHON_BUILD_ROOT%\unicodedata_d.pyd"		"%OUT_CONSOLEDEBUG64_DIR%\unicodedata_d.pyd"
copy "%PYTHON_BUILD_ROOT%\winsound_d.pyd"			"%OUT_CONSOLEDEBUG64_DIR%\winsound_d.pyd"

echo /////////%0 done